monitor.alsa.rules = [
	{
		matches = [
			{
				alsa.card_name = "JDS Labs Element IV"
			}
		]
		actions = {
			update-props = {
				audio.rate = 192000
				channelmix.lock-volumes = true
				resample.quality = 14
			}
		}
	}
]
