#!/bin/sh
if [ "$1" = "0000000000000000000000000000000000000000" ]; then
    if [[ -f /etc/os-release ]] && grep -q oxide.computer /etc/os-release; then
        git config --local user.email iliana@oxide.computer
    fi

    case $(git config --get remote.origin.url) in
        git@github.com:oxidecomputer/* | https://github.com/oxidecomputer/*)
            git config --local user.email iliana@oxide.computer
            ;;
    esac
fi
