#!/bin/sh
if [ "$1" = "0000000000000000000000000000000000000000" ]; then
    case $(git config --get remote.origin.url) in
        git@github.com:oxidecomputer/* | https://github.com/oxidecomputer/*)
            git config --local user.email iliana@oxide.computer
            ;;
    esac
fi
