tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"

brew "python@3.9", link: false
brew "python@3.10", link: true

brew "ansible"
brew "aws-sso-util"
brew "awscli"
brew "bash"
brew "bash-completion@2"
brew "bitwarden-cli"
brew "black"
brew "cmake"
brew "colima"
brew "coreutils"
brew "exa"
brew "ffmpeg"
brew "flake8"
brew "git"
brew "gnupg"
brew "go"
brew "htop"
brew "isort"
brew "jq"
brew "mas"
brew "moreutils"
brew "mpv"
brew "neofetch"
brew "ninja"
brew "node"
brew "optipng"
brew "opus-tools"
brew "pipenv"
brew "pipx"
brew "pngcrush"
brew "pv"
brew "rename"
brew "restic"
brew "ripgrep"
brew "rustup-init"
brew "shellcheck"
brew "subversion"
brew "syncthing", restart_service: true
brew "telnet"
brew "tmux"
brew "tokei"
brew "vim"
brew "watch"
brew "yt-dlp"
brew "zola"
brew "zstd"
cask "affinity-designer"
cask "affinity-publisher"
cask "firefox"
cask "font-iosevka"
cask "font-lora"
cask "font-open-sans"
cask "font-source-code-pro"
cask "hot"
cask "kitty"
cask "mgba"
cask "netnewswire"
cask "notunes"
mas "Amphetamine", id: 937984704
mas "PCalc", id: 403504866
mas "Tailscale", id: 1475387142
mas "iA Writer", id: 775737590
