#!/bin/bash
# creates an audio CD TOC with CD-TEXT for use with:
# `cdrdao write --driver generic-mmc:0x10 burn.toc`

set -euo pipefail

tag() {
    metaflac --no-utf8-convert --show-tag="$1" "$2" | head -n 1 | cut -d = -f 2-
}

cat <<EOF
CD_DA
CD_TEXT {
    LANGUAGE_MAP {
        0 : EN
    }
    LANGUAGE 0 {
        TITLE "$(tag album "$1")"
        PERFORMER "$(tag albumartist "$1")"
    }
}
EOF

while (( $# )); do
    sox "$1" -r 44100 -b 16 "${1%.flac}.wav"
    cat <<EOF

TRACK AUDIO
CD_TEXT {
    LANGUAGE 0 {
        TITLE "$(tag title "$1")"
        PERFORMER "$(tag artist "$1")"
    }
}
FILE "${1%.flac}.wav" 0
EOF
    shift
done

cdrdao toc-info "$(realpath --relative-to="$PWD" /proc/$$/fd/1)" 1>&2
