#!/bin/bash
set -euo pipefail
hash jq pipx restic

if [[ $# -lt 1 ]]; then
    >&2 echo "usage: restic.sh COMMAND [OPTIONS]"
    exit 1
fi
COMMAND=$1
shift

credentials_json="$(pipx run aws-sso-util credential-process --profile backups)"
AWS_ACCESS_KEY_ID="$(jq -r .AccessKeyId <<<"$credentials_json")"
export AWS_ACCESS_KEY_ID
AWS_SECRET_ACCESS_KEY="$(jq -r .SecretAccessKey <<<"$credentials_json")"
export AWS_SECRET_ACCESS_KEY
AWS_SESSION_TOKEN="$(jq -r .SessionToken <<<"$credentials_json")"
export AWS_SESSION_TOKEN

repo=$(cat ~/.config/dotfiles/.resticrepo)
passfile=~/.config/dotfiles/.resticpass

case "$COMMAND" in
    backup)
        cd ~ || exit
        exclude_file=$(mktemp)
        # shellcheck disable=SC2046
        find $(cat ~/.config/dotfiles/resticignore) -maxdepth 0 2>/dev/null >"$exclude_file" || :
        exec restic backup -r "$repo" --password-file "$passfile" \
            --exclude-caches --exclude-file "$exclude_file" "$@" \
            .
        ;;
    *)
        exec restic "$COMMAND" -r "$repo" --password-file "$passfile" "$@"
        ;;
esac
