theme = "iliana"

[editor]
auto-completion = false
bufferline = "multiple"
color-modes = true
cursorline = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true

[editor.lsp]
# https://github.com/helix-editor/helix/issues/5827 someday
auto-signature-help = false
